// <auto-generated />
using System;
using GarageOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageOS.Infrastructure.Data.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827140401_MakeGaragesAccountActiveIndexUnique")]
    partial class MakeGaragesAccountActiveIndexUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageOS.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTimeOffset?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_subscription_status", "subscription_status IN ('trial','active','past_due','suspended','cancelled','expired')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<bool>("IsFleet")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fleet");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("customers_garage_idx");

                    b.HasIndex("GarageId", "Phone")
                        .HasDatabaseName("customers_phone_idx");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Estimate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalMethod")
                        .HasColumnType("text")
                        .HasColumnName("approval_method");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedByName")
                        .HasColumnType("text")
                        .HasColumnName("approved_by_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ParentEstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_estimate_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_estimates");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_estimates_created_by");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("estimates_garage_idx");

                    b.HasIndex("JobId")
                        .HasDatabaseName("estimates_job_idx");

                    b.HasIndex("ParentEstimateId")
                        .HasDatabaseName("estimates_parent_idx")
                        .HasFilter("parent_estimate_id IS NOT NULL");

                    b.ToTable("estimates", null, t =>
                        {
                            t.HasCheckConstraint("ck_estimates_status", "status IN ('draft','sent','approved','partially_approved','rejected','superseded')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.EstimateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("approval_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("estimate_id");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_estimate_items");

                    b.HasIndex("EstimateId")
                        .HasDatabaseName("estimate_items_estimate_idx");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("estimate_items_garage_idx");

                    b.ToTable("estimate_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_estimate_items_approval_status", "approval_status IN ('pending','approved','rejected')");

                            t.HasCheckConstraint("ck_estimate_items_type", "type IN ('part','labor','service','misc')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_garages");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_garages_deleted_by");

                    b.HasIndex(new[] { "AccountId" }, "garages_account_active_idx")
                        .IsUnique()
                        .HasDatabaseName("garages_account_active_idx")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex(new[] { "AccountId" }, "garages_account_idx")
                        .HasDatabaseName("garages_account_idx");

                    b.ToTable("garages", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.GarageSequence", b =>
                {
                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<long>("NextInvoiceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_invoice_number");

                    b.Property<long>("NextJobNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_job_number");

                    b.HasKey("GarageId")
                        .HasName("pk_garage_sequences");

                    b.ToTable("garage_sequences", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.GarageSettings", b =>
                {
                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<bool>("AllowDeliveryWithBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_delivery_with_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal>("DefaultLaborRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_labor_rate");

                    b.Property<decimal>("DiagnosisFeeAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("diagnosis_fee_amount");

                    b.Property<string>("DiagnosisFeePolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_fee_policy");

                    b.Property<decimal>("DiscountLimitPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_limit_percent");

                    b.Property<string>("DisplayCurrency")
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("EstimateApprovalThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimate_approval_threshold");

                    b.Property<string>("ExtraSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_settings");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_prefix");

                    b.Property<string>("TaxLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_label");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WarrantyMileageKm")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_mileage_km");

                    b.Property<int>("WarrantyPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_period_days");

                    b.Property<string>("WorkingHoursClose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("working_hours_close");

                    b.Property<string>("WorkingHoursOpen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("working_hours_open");

                    b.HasKey("GarageId")
                        .HasName("pk_garage_settings");

                    b.ToTable("garage_settings", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DisplayRateSnapshot")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("display_rate_snapshot");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_paid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invoices_created_by");

                    b.HasIndex("JobId")
                        .HasDatabaseName("invoices_job_idx");

                    b.HasIndex("VoidedBy")
                        .HasDatabaseName("ix_invoices_voided_by");

                    b.HasIndex("GarageId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("invoices_number_idx");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_status", "status IN ('unpaid','partial','paid','voided','written_off')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvisorNotes")
                        .HasColumnType("text")
                        .HasColumnName("advisor_notes");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerComplaint")
                        .HasColumnType("text")
                        .HasColumnName("customer_complaint");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("CustomerWaiting")
                        .HasColumnType("boolean")
                        .HasColumnName("customer_waiting");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text")
                        .HasColumnName("deletion_reason");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<bool>("IsWarrantyReturn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warranty_return");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_number");

                    b.Property<int?>("MileageAtIntake")
                        .HasColumnType("integer")
                        .HasColumnName("mileage_at_intake");

                    b.Property<bool>("Overnight")
                        .HasColumnType("boolean")
                        .HasColumnName("overnight");

                    b.Property<string>("OvernightNote")
                        .HasColumnType("text")
                        .HasColumnName("overnight_note");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_job_id");

                    b.Property<Guid?>("PrimaryMechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_mechanic_id");

                    b.Property<DateTimeOffset?>("PromisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promised_at");

                    b.Property<Guid?>("SecondaryMechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_mechanic_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("CancelledBy")
                        .HasDatabaseName("ix_jobs_cancelled_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_jobs_created_by");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("jobs_customer_idx");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_jobs_deleted_by");

                    b.HasIndex("ParentJobId")
                        .HasDatabaseName("jobs_parent_job_idx")
                        .HasFilter("parent_job_id IS NOT NULL");

                    b.HasIndex("PrimaryMechanicId")
                        .HasDatabaseName("jobs_mechanic_idx");

                    b.HasIndex("SecondaryMechanicId")
                        .HasDatabaseName("jobs_secondary_mechanic_idx")
                        .HasFilter("secondary_mechanic_id IS NOT NULL");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("jobs_vehicle_idx");

                    b.HasIndex("GarageId", "JobNumber")
                        .IsUnique()
                        .HasDatabaseName("jobs_number_idx");

                    b.HasIndex("GarageId", "Status")
                        .HasDatabaseName("jobs_garage_status_idx")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_status", "status IN ('checked_in','diagnosing','waiting_approval','waiting_parts','ready_to_repair','repairing','qc','ready','delivered','cancelled')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.JobHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_job_history");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_job_history_actor_id");

                    b.HasIndex("GarageId", "CreatedAt")
                        .HasDatabaseName("job_history_garage_idx");

                    b.HasIndex("JobId", "CreatedAt")
                        .HasDatabaseName("job_history_job_idx");

                    b.ToTable("job_history", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.JobPart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_at");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<DateTimeOffset?>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("IssueNote")
                        .HasColumnType("text")
                        .HasColumnName("issue_note");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("text")
                        .HasColumnName("return_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SuppliedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplied_by");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierNameSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("supplier_name_snapshot");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_parts");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("job_parts_garage_idx");

                    b.HasIndex("JobId")
                        .HasDatabaseName("job_parts_job_idx");

                    b.ToTable("job_parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_parts_status", "status IN ('needed','searching','ordered','arrived','installed','returned','issue_wrong_part','issue_damaged')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("payments_invoice_idx");

                    b.HasIndex("RecordedBy")
                        .HasDatabaseName("ix_payments_recorded_by");

                    b.HasIndex("GarageId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("payments_idempotency_idx");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_method", "method IN ('cash','card','bank_transfer','cheque','other')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("refresh_tokens_token_hash_idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("refresh_tokens_user_idx");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.RepairTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedMechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_mechanic_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("OutsourceBilled")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("outsource_billed");

                    b.Property<decimal?>("OutsourceCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("outsource_cost");

                    b.Property<DateTimeOffset?>("OutsourceReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outsource_returned_at");

                    b.Property<DateTimeOffset?>("OutsourceSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outsource_sent_at");

                    b.Property<string>("OutsourceSupplier")
                        .HasColumnType("text")
                        .HasColumnName("outsource_supplier");

                    b.Property<bool>("Outsourced")
                        .HasColumnType("boolean")
                        .HasColumnName("outsourced");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_repair_tasks");

                    b.HasIndex("AssignedMechanicId")
                        .HasDatabaseName("repair_tasks_mechanic_idx")
                        .HasFilter("assigned_mechanic_id IS NOT NULL");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("repair_tasks_garage_idx");

                    b.HasIndex("JobId")
                        .HasDatabaseName("repair_tasks_job_idx");

                    b.ToTable("repair_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_repair_tasks_status", "status IN ('pending','in_progress','paused','completed','cancelled')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_idx");

                    b.HasIndex("GarageId")
                        .HasDatabaseName("users_garage_idx");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('owner','manager','advisor','mechanic','accountant')");
                        });
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentMileage")
                        .HasColumnType("integer")
                        .HasColumnName("current_mileage");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Drivetrain")
                        .HasColumnType("text")
                        .HasColumnName("drivetrain");

                    b.Property<string>("Engine")
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<string>("EngineCode")
                        .HasColumnType("text")
                        .HasColumnName("engine_code");

                    b.Property<string>("FuelType")
                        .HasColumnType("text")
                        .HasColumnName("fuel_type");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid")
                        .HasColumnName("garage_id");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("PlateCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate_country");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate_number");

                    b.Property<string>("Transmission")
                        .HasColumnType("text")
                        .HasColumnName("transmission");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("vehicles_customer_idx");

                    b.HasIndex("GarageId", "Vin")
                        .HasDatabaseName("vehicles_vin_idx");

                    b.HasIndex("GarageId", "PlateNumber", "PlateCountry")
                        .IsUnique()
                        .HasDatabaseName("vehicles_plate_idx");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Customer", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_customers_garages_garage_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Estimate", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_estimates_users_created_by");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estimates_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estimates_jobs_job_id");

                    b.HasOne("GarageOS.Domain.Entities.Estimate", null)
                        .WithMany()
                        .HasForeignKey("ParentEstimateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_estimates_estimates_parent_estimate_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.EstimateItem", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Estimate", null)
                        .WithMany()
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estimate_items_estimates_estimate_id");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estimate_items_garages_garage_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Garage", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_garages_accounts_account_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_garages_users_deleted_by");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.GarageSequence", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithOne()
                        .HasForeignKey("GarageOS.Domain.Entities.GarageSequence", "GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_garage_sequences_garages_garage_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.GarageSettings", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithOne()
                        .HasForeignKey("GarageOS.Domain.Entities.GarageSettings", "GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_garage_settings_garages_garage_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_invoices_users_created_by");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_jobs_job_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VoidedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_invoices_users_voided_by");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Job", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_jobs_users_cancelled_by");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_users_created_by");

                    b.HasOne("GarageOS.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_customers_customer_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_jobs_users_deleted_by");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_jobs_jobs_parent_job_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PrimaryMechanicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_jobs_users_primary_mechanic_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SecondaryMechanicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_jobs_users_secondary_mechanic_id");

                    b.HasOne("GarageOS.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_vehicles_vehicle_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.JobHistoryEntry", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_job_history_users_actor_id");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_job_history_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_job_history_jobs_job_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.JobPart", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_job_parts_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_job_parts_jobs_job_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_payments_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_payments_users_recorded_by");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.RepairTask", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedMechanicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_repair_tasks_users_assigned_mechanic_id");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_repair_tasks_garages_garage_id");

                    b.HasOne("GarageOS.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_repair_tasks_jobs_job_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.User", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_users_garages_garage_id");
                });

            modelBuilder.Entity("GarageOS.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("GarageOS.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_customers_customer_id");

                    b.HasOne("GarageOS.Domain.Entities.Garage", null)
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_garages_garage_id");
                });
#pragma warning restore 612, 618
        }
    }
}
